name: "❓ Question (en)"
description: "Ask a question or request clarification about Lino"
title: "[Question] "
labels: ["question", "triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe your question clearly.
    validations:
      required: true

  - type: input
    id: context
    attributes:
      label: Context (optional)
      description: Provide context. Lino version, OS, account type, etc.
      placeholder: "Lino v1.2.3, Windows 11, Free account"
